// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/memo"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MemoUpdate is the builder for updating Memo entities.
type MemoUpdate struct {
	config
	hooks    []Hook
	mutation *MemoMutation
}

// Where appends a list predicates to the MemoUpdate builder.
func (_u *MemoUpdate) Where(ps ...predicate.Memo) *MemoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MemoUpdate) SetUserID(v int64) *MemoUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemoUpdate) SetNillableUserID(v *int64) *MemoUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MemoUpdate) AddUserID(v int64) *MemoUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *MemoUpdate) SetTitle(v string) *MemoUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MemoUpdate) SetNillableTitle(v *string) *MemoUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MemoUpdate) SetContent(v string) *MemoUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MemoUpdate) SetNillableContent(v *string) *MemoUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *MemoUpdate) SetPinned(v bool) *MemoUpdate {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *MemoUpdate) SetNillablePinned(v *bool) *MemoUpdate {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemoUpdate) SetUpdatedAt(v time.Time) *MemoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MemoMutation object of the builder.
func (_u *MemoUpdate) Mutation() *MemoMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemoUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemoUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := memo.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Memo.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := memo.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Memo.content": %w`, err)}
		}
	}
	return nil
}

func (_u *MemoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memo.Table, memo.Columns, sqlgraph.NewFieldSpec(memo.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(memo.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(memo.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(memo.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(memo.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(memo.FieldPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemoUpdateOne is the builder for updating a single Memo entity.
type MemoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemoMutation
}

// SetUserID sets the "user_id" field.
func (_u *MemoUpdateOne) SetUserID(v int64) *MemoUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemoUpdateOne) SetNillableUserID(v *int64) *MemoUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MemoUpdateOne) AddUserID(v int64) *MemoUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *MemoUpdateOne) SetTitle(v string) *MemoUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MemoUpdateOne) SetNillableTitle(v *string) *MemoUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MemoUpdateOne) SetContent(v string) *MemoUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MemoUpdateOne) SetNillableContent(v *string) *MemoUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *MemoUpdateOne) SetPinned(v bool) *MemoUpdateOne {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *MemoUpdateOne) SetNillablePinned(v *bool) *MemoUpdateOne {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemoUpdateOne) SetUpdatedAt(v time.Time) *MemoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MemoMutation object of the builder.
func (_u *MemoUpdateOne) Mutation() *MemoMutation {
	return _u.mutation
}

// Where appends a list predicates to the MemoUpdate builder.
func (_u *MemoUpdateOne) Where(ps ...predicate.Memo) *MemoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemoUpdateOne) Select(field string, fields ...string) *MemoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Memo entity.
func (_u *MemoUpdateOne) Save(ctx context.Context) (*Memo, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoUpdateOne) SaveX(ctx context.Context) *Memo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemoUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := memo.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Memo.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := memo.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Memo.content": %w`, err)}
		}
	}
	return nil
}

func (_u *MemoUpdateOne) sqlSave(ctx context.Context) (_node *Memo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memo.Table, memo.Columns, sqlgraph.NewFieldSpec(memo.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Memo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memo.FieldID)
		for _, f := range fields {
			if !memo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(memo.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(memo.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(memo.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(memo.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(memo.FieldPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memo.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Memo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
