// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/memo"
)

// MemoCreate is the builder for creating a Memo entity.
type MemoCreate struct {
	config
	mutation *MemoMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *MemoCreate) SetUserID(v int64) *MemoCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *MemoCreate) SetTitle(v string) *MemoCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *MemoCreate) SetContent(v string) *MemoCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetPinned sets the "pinned" field.
func (_c *MemoCreate) SetPinned(v bool) *MemoCreate {
	_c.mutation.SetPinned(v)
	return _c
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_c *MemoCreate) SetNillablePinned(v *bool) *MemoCreate {
	if v != nil {
		_c.SetPinned(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MemoCreate) SetCreatedAt(v time.Time) *MemoCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MemoCreate) SetNillableCreatedAt(v *time.Time) *MemoCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MemoCreate) SetUpdatedAt(v time.Time) *MemoCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MemoCreate) SetNillableUpdatedAt(v *time.Time) *MemoCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the MemoMutation object of the builder.
func (_c *MemoCreate) Mutation() *MemoMutation {
	return _c.mutation
}

// Save creates the Memo in the database.
func (_c *MemoCreate) Save(ctx context.Context) (*Memo, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemoCreate) SaveX(ctx context.Context) *Memo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemoCreate) defaults() {
	if _, ok := _c.mutation.Pinned(); !ok {
		v := memo.DefaultPinned
		_c.mutation.SetPinned(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := memo.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := memo.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemoCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Memo.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Memo.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := memo.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Memo.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Memo.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := memo.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Memo.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pinned(); !ok {
		return &ValidationError{Name: "pinned", err: errors.New(`ent: missing required field "Memo.pinned"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Memo.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Memo.updated_at"`)}
	}
	return nil
}

func (_c *MemoCreate) sqlSave(ctx context.Context) (*Memo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemoCreate) createSpec() (*Memo, *sqlgraph.CreateSpec) {
	var (
		_node = &Memo{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memo.Table, sqlgraph.NewFieldSpec(memo.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(memo.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(memo.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(memo.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Pinned(); ok {
		_spec.SetField(memo.FieldPinned, field.TypeBool, value)
		_node.Pinned = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(memo.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(memo.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Memo.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MemoUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *MemoCreate) OnConflict(opts ...sql.ConflictOption) *MemoUpsertOne {
	_c.conflict = opts
	return &MemoUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Memo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MemoCreate) OnConflictColumns(columns ...string) *MemoUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MemoUpsertOne{
		create: _c,
	}
}

type (
	// MemoUpsertOne is the builder for "upsert"-ing
	//  one Memo node.
	MemoUpsertOne struct {
		create *MemoCreate
	}

	// MemoUpsert is the "OnConflict" setter.
	MemoUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *MemoUpsert) SetUserID(v int64) *MemoUpsert {
	u.Set(memo.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MemoUpsert) UpdateUserID() *MemoUpsert {
	u.SetExcluded(memo.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *MemoUpsert) AddUserID(v int64) *MemoUpsert {
	u.Add(memo.FieldUserID, v)
	return u
}

// SetTitle sets the "title" field.
func (u *MemoUpsert) SetTitle(v string) *MemoUpsert {
	u.Set(memo.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MemoUpsert) UpdateTitle() *MemoUpsert {
	u.SetExcluded(memo.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *MemoUpsert) SetContent(v string) *MemoUpsert {
	u.Set(memo.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MemoUpsert) UpdateContent() *MemoUpsert {
	u.SetExcluded(memo.FieldContent)
	return u
}

// SetPinned sets the "pinned" field.
func (u *MemoUpsert) SetPinned(v bool) *MemoUpsert {
	u.Set(memo.FieldPinned, v)
	return u
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *MemoUpsert) UpdatePinned() *MemoUpsert {
	u.SetExcluded(memo.FieldPinned)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MemoUpsert) SetUpdatedAt(v time.Time) *MemoUpsert {
	u.Set(memo.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MemoUpsert) UpdateUpdatedAt() *MemoUpsert {
	u.SetExcluded(memo.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Memo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MemoUpsertOne) UpdateNewValues() *MemoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(memo.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Memo.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MemoUpsertOne) Ignore() *MemoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MemoUpsertOne) DoNothing() *MemoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MemoCreate.OnConflict
// documentation for more info.
func (u *MemoUpsertOne) Update(set func(*MemoUpsert)) *MemoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MemoUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *MemoUpsertOne) SetUserID(v int64) *MemoUpsertOne {
	return u.Update(func(s *MemoUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *MemoUpsertOne) AddUserID(v int64) *MemoUpsertOne {
	return u.Update(func(s *MemoUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MemoUpsertOne) UpdateUserID() *MemoUpsertOne {
	return u.Update(func(s *MemoUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *MemoUpsertOne) SetTitle(v string) *MemoUpsertOne {
	return u.Update(func(s *MemoUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MemoUpsertOne) UpdateTitle() *MemoUpsertOne {
	return u.Update(func(s *MemoUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *MemoUpsertOne) SetContent(v string) *MemoUpsertOne {
	return u.Update(func(s *MemoUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MemoUpsertOne) UpdateContent() *MemoUpsertOne {
	return u.Update(func(s *MemoUpsert) {
		s.UpdateContent()
	})
}

// SetPinned sets the "pinned" field.
func (u *MemoUpsertOne) SetPinned(v bool) *MemoUpsertOne {
	return u.Update(func(s *MemoUpsert) {
		s.SetPinned(v)
	})
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *MemoUpsertOne) UpdatePinned() *MemoUpsertOne {
	return u.Update(func(s *MemoUpsert) {
		s.UpdatePinned()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MemoUpsertOne) SetUpdatedAt(v time.Time) *MemoUpsertOne {
	return u.Update(func(s *MemoUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MemoUpsertOne) UpdateUpdatedAt() *MemoUpsertOne {
	return u.Update(func(s *MemoUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MemoUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MemoCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MemoUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MemoUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MemoUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MemoCreateBulk is the builder for creating many Memo entities in bulk.
type MemoCreateBulk struct {
	config
	err      error
	builders []*MemoCreate
	conflict []sql.ConflictOption
}

// Save creates the Memo entities in the database.
func (_c *MemoCreateBulk) Save(ctx context.Context) ([]*Memo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Memo, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemoCreateBulk) SaveX(ctx context.Context) []*Memo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Memo.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MemoUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *MemoCreateBulk) OnConflict(opts ...sql.ConflictOption) *MemoUpsertBulk {
	_c.conflict = opts
	return &MemoUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Memo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MemoCreateBulk) OnConflictColumns(columns ...string) *MemoUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MemoUpsertBulk{
		create: _c,
	}
}

// MemoUpsertBulk is the builder for "upsert"-ing
// a bulk of Memo nodes.
type MemoUpsertBulk struct {
	create *MemoCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Memo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MemoUpsertBulk) UpdateNewValues() *MemoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(memo.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Memo.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MemoUpsertBulk) Ignore() *MemoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MemoUpsertBulk) DoNothing() *MemoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MemoCreateBulk.OnConflict
// documentation for more info.
func (u *MemoUpsertBulk) Update(set func(*MemoUpsert)) *MemoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MemoUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *MemoUpsertBulk) SetUserID(v int64) *MemoUpsertBulk {
	return u.Update(func(s *MemoUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *MemoUpsertBulk) AddUserID(v int64) *MemoUpsertBulk {
	return u.Update(func(s *MemoUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MemoUpsertBulk) UpdateUserID() *MemoUpsertBulk {
	return u.Update(func(s *MemoUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *MemoUpsertBulk) SetTitle(v string) *MemoUpsertBulk {
	return u.Update(func(s *MemoUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MemoUpsertBulk) UpdateTitle() *MemoUpsertBulk {
	return u.Update(func(s *MemoUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *MemoUpsertBulk) SetContent(v string) *MemoUpsertBulk {
	return u.Update(func(s *MemoUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MemoUpsertBulk) UpdateContent() *MemoUpsertBulk {
	return u.Update(func(s *MemoUpsert) {
		s.UpdateContent()
	})
}

// SetPinned sets the "pinned" field.
func (u *MemoUpsertBulk) SetPinned(v bool) *MemoUpsertBulk {
	return u.Update(func(s *MemoUpsert) {
		s.SetPinned(v)
	})
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *MemoUpsertBulk) UpdatePinned() *MemoUpsertBulk {
	return u.Update(func(s *MemoUpsert) {
		s.UpdatePinned()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MemoUpsertBulk) SetUpdatedAt(v time.Time) *MemoUpsertBulk {
	return u.Update(func(s *MemoUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MemoUpsertBulk) UpdateUpdatedAt() *MemoUpsertBulk {
	return u.Update(func(s *MemoUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MemoUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MemoCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MemoCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MemoUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
